In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Candidatos.csv', low_memory=False)

In [ ]:
df.head()

,ano,id_eleicao,tipo_eleicao,data_eleicao,sigla_uf,id_municipio,id_municipio_tse,titulo_eleitoral,cpf,sequencial,...,idade,genero,instrucao,ocupacao,estado_civil,nacionalidade,sigla_uf_nascimento,municipio_nascimento,email,raca
0,1998,1998001,eleicao ordinaria,1998-10-04,MG,NaN,NaN,3.098924e+10,27563472649,130001307336031,...,41.0,masculino,NaN,proprietario de estabelecimento comercial,casado(a),brasileira,NaN,NaN,NaN,NaN
1,1998,1998001,eleicao ordinaria,1998-10-04,RO,NaN,NaN,4.870823e+08,02643049268,220002210002211,...,44.0,masculino,ensino medio completo,proprietario de estabelecimento comercial,solteiro(a),brasileira,AC,Tarauaca,NaN,NaN
2,1998,1998001,eleicao ordinaria,1998-10-04,AC,NaN,NaN,8.284125e+08,09138374234,100000106011011,...,38.0,masculino,ensino superior incompleto,membros do poder legislativo: senador deputado...,divorciado(a),brasileira,AC,Feijo,NaN,NaN
3,1998,1998001,eleicao ordinaria,1998-10-04,AC,NaN,NaN,2.475425e+08,06665543234,100000106025331,...,52.0,masculino,ensino superior completo,advogado,casado(a),brasileira,AC,Rio Branco,NaN,NaN
4,1998,1998001,eleicao ordinaria,1998-10-04,AC,NaN,NaN,4.027244e+07,01546503234,100000107111091,...,52.0,masculino,ensino medio incompleto,membros do poder executivo: presidente ministr...,divorciado(a),brasileira,AC,Feijo,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3354725 entries, 0 to 3354724
Data columns (total 28 columns):
 #   Column                Dtype
---  ------                -----
 0   ano                   int64
 1   id_eleicao            int64
 2   tipo_eleicao          object
 3   data_eleicao          object
 4   sigla_uf              object
 5   id_municipio          float64
 6   id_municipio_tse      float64
 7   titulo_eleitoral      float64
 8   cpf                   object
 9   sequencial            int64
 10  numero                float64
 11  nome                  object
 12  nome_urna             object
 13  numero_partido        int64
 14  sigla_partido         object
 15  cargo                 object
 16  situacao              object
 17  data_nascimento       object
 18  idade                 float64
 19  genero                object
 20  instrucao             object
 21  ocupacao              object
 22  estado_civil          object
 23  nacionalidade         object
 24  sigla_uf_nascimento   object
 25  municipio_nascimento  object
 26  email                 object
 27  raca                  object
dtypes: float64(5), int64(4), object(19)
memory usage: 716.6+ MB

In [ ]:
df.shape

(3354725, 28)

In [ ]:
df.columns

Index(['ano', 'id_eleicao', 'tipo_eleicao', 'data_eleicao', 'sigla_uf',
       'id_municipio', 'id_municipio_tse', 'titulo_eleitoral', 'cpf',
       'sequencial', 'numero', 'nome', 'nome_urna', 'numero_partido',
       'sigla_partido', 'cargo', 'situacao', 'data_nascimento', 'idade',
       'genero', 'instrucao', 'ocupacao', 'estado_civil', 'nacionalidade',
       'sigla_uf_nascimento', 'municipio_nascimento', 'email', 'raca'],
      dtype='object')

In [ ]:
df.groupby('situacao').size()

situacao
aguardando julgamento                                 64
cancelado                                           3366
cancelado com recurso                                 12
cassado                                             5012
cassado com recurso                                  827
deferido                                         2730698
deferido com recurso                                6765
falecido                                             725
falecimento                                          218
impugnado                                              3
indeferido                                         89779
indeferido com recurso                             10117
inelegivel                                           487
nao conhecimento do pedido                           714
pedido nao conhecido                                 403
pedido nao conhecido com recurso                      17
pendente de julgamento                               215
renuncia                                           59421
sub judice                                          2831
substituto majoritario pendente de julgamento         57
substituto pendente de julgamento                    212
dtype: int64

In [ ]:
df.groupby(['ano','id_eleicao','tipo_eleicao']).size()

ano   id_eleicao  tipo_eleicao
1994  1994001     eleicao ordinaria                       5670
1996  1996001     eleicao ordinaria                      10356
1998  1998001     eleicao ordinaria                      15023
2000  2000001     eleicao ordinaria                     398654
2002  200201      eleicao ordinaria                      17990
                                                         ...
2020  627         suplementar de turvelandia - go            4
      629         suplementar sao francisco de assis         4
2022  544         eleicao ordinaria                         23
      546         eleicao ordinaria                      28949
2024  619         eleicao ordinaria                     462821
Length: 503, dtype: int64

**Limpar base para conter apenas:**

*   deferido
*   deferido com recurso

In [ ]:
df_deferido = df[(df['situacao'] == 'deferido') | (df['situacao'] == 'deferido com recurso')]

In [ ]:
df_deferido.reset_index(inplace=True)

In [ ]:
df_deferido = df_deferido.drop(columns=['index'])

In [ ]:
df_deferido

,ano,id_eleicao,tipo_eleicao,data_eleicao,sigla_uf,id_municipio,id_municipio_tse,titulo_eleitoral,cpf,sequencial,...,idade,genero,instrucao,ocupacao,estado_civil,nacionalidade,sigla_uf_nascimento,municipio_nascimento,email,raca
0,2006,2006001,eleicao ordinaria,2006-10-01,AC,NaN,NaN,2.145152e+09,03766489291,10309,...,52.0,masculino,ensino superior completo,economista,solteiro(a),brasileira,AC,Tarauacá,chagasfreitas@yahoo.com,NaN
1,2006,2006001,eleicao ordinaria,2006-10-01,AC,NaN,NaN,4.988525e+08,19655924220,10002,...,42.0,masculino,ensino medio completo,outros,casado(a),brasileira,AC,Rio Branco,beniciodias@click21.com.br,NaN
2,2006,2006001,eleicao ordinaria,2006-10-01,AC,NaN,NaN,1.649702e+10,50791524272,10023,...,36.0,feminino,ensino superior completo,outros,casado(a),brasileira,AC,Senador Guiomard,paulo@ufac.br,NaN
3,2006,2006001,eleicao ordinaria,2006-10-01,AC,NaN,NaN,1.426382e+09,02190710200,10031,...,54.0,masculino,ensino superior completo,deputado,casado(a),brasileira,AC,Tarauacá,dep.nilsonmourao@camara.gov.br,NaN
4,2006,2006001,eleicao ordinaria,2006-10-01,AC,NaN,NaN,2.645724e+08,21630755249,10032,...,42.0,masculino,ensino superior completo,deputado,casado(a),brasileira,CE,Cruzeiro Do Sul,dep.henriqueafonso@camara.gov.br,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2737458,2004,200412,eleicao ordinaria,2004-10-03,GO,5208707.0,93734.0,2.676752e+10,70927880130,720,...,33.0,masculino,ensino medio completo,feirante ambulante e mascate,solteiro(a),brasileira,GO,Ivolandia,NaN,NaN
2737459,2004,200412,eleicao ordinaria,2004-10-03,GO,5213053.0,92347.0,1.407867e+10,25864432172,97,...,41.0,masculino,ensino superior incompleto,administrador,divorciado(a),brasileira,DF,Brasília,NaN,NaN
2737460,2004,200412,eleicao ordinaria,2004-10-03,GO,5215603.0,95095.0,7.023061e+09,32048343104,163,...,43.0,masculino,ensino fundamental completo,comerciante,casado(a),brasileira,GO,Anapolis,NaN,NaN
2737461,2004,200412,eleicao ordinaria,2004-10-03,GO,5217401.0,95451.0,3.490349e+10,49956809187,94,...,35.0,masculino,ensino fundamental incompleto,outros,casado(a),brasileira,GO,Pires Do Rio,NaN,NaN
2737462,2004,200412,eleicao ordinaria,2004-10-03,GO,5221858.0,93300.0,4.698462e+09,24455105115,279,...,42.0,masculino,ensino superior incompleto,locutor e comentarista de radio e televisao e ...,solteiro(a),brasileira,BA,Mundo Novo,NaN,NaN

In [ ]:
df_deferido[['numero', 'nome_urna','numero_partido','nome']]

,numero,nome_urna,numero_partido,nome
0,255.0,Chagas Freitas,25,Francisco Chagas Da Costa Freitas
1,277.0,Chico Benicio,27,Francisco Chagas Benício Dias
2,1112.0,Antonia Lúcia,11,Antonia Luciléia Cruz Ramos Câmara
3,1313.0,Nilson Mourão,13,Nilson Moura Leite Mourão
4,1345.0,Henrique Afonso,13,Henrique Afonso Soares Lima
...,...,...,...,...
2737458,70999.0,Romildo Gomes,70,Romildo Gomes
2737459,70123.0,Washington,70,Washington Da Costa E Silva
2737460,70633.0,Helio Peixoto,70,Helio Carvalho Peixoto
2737461,70100.0,Cicero,70,Cicero Antonio Dutra De Moraes
2737462,70225.0,Franc Pereira,70,Francisco Pereira Dos Santos

### **TABELA DE CANDIDATOS**

In [ ]:
# 1. Ajuste para tabela do BD
mapeamento = {
    "sequencial": "sequencial_candidato",
    "titulo_eleitoral": "titulo_eleitoral",
    "id_eleicao": "id_eleicao",
    "numero_partido": "numero_partido",
    "id_municipio": "id_municipio",
    "cargo": "cargo",
    "numero": "numero_urna",
    "nome_urna": "nome_urna",
    "situacao": "situacao"
}

# 2. Filtrar apenas as colunas desejadas e renomeá-las
df_candidatos = df_deferido[list(mapeamento.keys())].rename(columns=mapeamento).copy()


# Visualizar o resultado
df_candidatos.head()

,sequencial_candidato,titulo_eleitoral,id_eleicao,numero_partido,id_municipio,cargo,numero_urna,nome_urna,situacao
0,10309,2.145152e+09,2006001,25,NaN,senador,255.0,Chagas Freitas,deferido
1,10002,4.988525e+08,2006001,27,NaN,senador,277.0,Chico Benicio,deferido
2,10023,1.649702e+10,2006001,11,NaN,deputado federal,1112.0,Antonia Lúcia,deferido
3,10031,1.426382e+09,2006001,13,NaN,deputado federal,1313.0,Nilson Mourão,deferido
4,10032,2.645724e+08,2006001,13,NaN,deputado federal,1345.0,Henrique Afonso,deferido

In [ ]:
# ==========================================
# ANÁLISE DE DUPLICATAS (CANDIDATURA)
# ==========================================

# 1. Identificar duplicatas na chave (sequencial_candidato)
duplicados_candidatura = df_candidatos.groupby('sequencial_candidato').size()
duplicados_acima_de_1  = duplicados_candidatura[duplicados_candidatura > 1].sort_values(ascending=False)

print(f"Total de sequencial_candidato com duplicidade: {len(duplicados_acima_de_1)}")
print("\nExemplo dos que mais se repetem (sequencial | Quantidade):")
print(duplicados_acima_de_1.head(20))

Total de sequencial_candidato com duplicidade: 421795

Exemplo dos que mais se repetem (sequencial | Quantidade):
sequencial_candidato
28    1973
11    1967
26    1964
12    1963
27    1959
31    1956
29    1953
14    1953
33    1951
21    1949
36    1946
10    1945
39    1945
23    1945
8     1944
25    1944
7     1943
15    1943
30    1943
17    1942
dtype: int64

In [ ]:
# 2. Investigar um exemplo para verificar se as linhas se complementam
exemplo_seq = duplicados_acima_de_1.index[0]  # caso queira conferir outros, basta trocar o numero
df_candidatos[df_candidatos['sequencial_candidato'] == exemplo_seq]

,sequencial_candidato,titulo_eleitoral,id_eleicao,numero_partido,id_municipio,cargo,numero_urna,nome_urna,situacao
99659,28,1.246774e+10,30,20,2801900.0,vereador,20000.0,Luciano Messias,deferido
210605,28,6.226341e+10,30,45,4106704.0,vereador,45000.0,Fabio,deferido
529870,28,3.596448e+10,2006001,29,NaN,vice-presidente,29.0,Pepe,deferido
639812,28,4.331835e+10,30,20,2929370.0,vereador,20123.0,Gerson,deferido
640582,28,8.275470e+09,30,36,3524006.0,vereador,36001.0,Ronaldo Da Kombi,deferido
...,...,...,...,...,...,...,...,...,...
2736076,28,2.869064e+10,200412,45,2310001.0,vereador,45666.0,Batista Da Mariana,deferido
2736371,28,2.707650e+10,200412,45,3151909.0,vereador,45123.0,Julio Campos,deferido
2736580,28,7.610434e+10,200412,45,3528502.0,vereador,45013.0,Angela De Almeida,deferido
2736913,28,2.192670e+10,200412,45,5214903.0,vereador,45456.0,Degilson,deferido
2737103,28,7.733432e+09,200412,27,5102504.0,vereador,27890.0,Davi,deferido

In [ ]:
df_dup_completos = df_candidatos[df_candidatos['sequencial_candidato'].duplicated(keep=False)]

print("--- DUPLICADOS POR CARGO E SEQUENCIAL_CANDIDATO ---")
print(
    df_dup_completos
    .groupby([ 'sequencial_candidato','id_eleicao'])
    .size()
    .sort_values(ascending=False)
    .reset_index(name='quantidade')
    .head(20)
)

--- DUPLICADOS POR CARGO E SEQUENCIAL_CANDIDATO ---
    sequencial_candidato  id_eleicao  quantidade
0                     28      200412        1949
1                     11      200412        1948
2                     12      200412        1945
3                     26      200412        1941
4                     27      200412        1937
5                     14      200412        1937
6                     31      200412        1935
7                     29      200412        1934
8                     17      200412        1931
9                     33      200412        1929
10                    21      200412        1928
11                    15      200412        1927
12                    36      200412        1925
13                    39      200412        1924
14                    23      200412        1923
15                    20      200412        1922
16                    25      200412        1922
17                    30      200412        1922
18                    16      200412        1921
19                    13      200412        1921

In [ ]:
df_dup = df_dup_completos \
    .groupby(['sequencial_candidato','id_eleicao','nome_urna', 'titulo_eleitoral']) \
    .size() \
    .sort_values(ascending=False) \
    .reset_index(name='quantidade') \
    .head(30)
df_dup

,sequencial_candidato,id_eleicao,nome_urna,titulo_eleitoral,quantidade
0,280000000002,143,Claudia Durans,4.226942e+10,1
1,1,30,Adilson,2.777832e+10,1
2,1,30,Almir,7.513432e+09,1
3,1,30,Antônio Maria,2.991408e+10,1
4,1,30,Dió,2.535805e+10,1
5,1,30,Dra. Lydia,4.668798e+10,1
6,1,30,Genildo Dos Santos,5.131019e+10,1
7,1,30,Jaime,1.615925e+10,1
8,1,30,Jose Luiz,1.442031e+09,1
9,270000010297,220,Crisley Machado,1.159486e+11,1
10,270000010297,47,Raimundo Contador,2.678671e+10,1
11,270000010296,220,Tatiane Arruda,3.156284e+10,1
12,270000010296,47,Marinalva,2.395477e+10,1
13,270000010295,220,Deuzimária,3.045353e+10,1
14,270000010295,47,Erica,3.831247e+10,1
15,270000010294,220,Vanessa Santos,3.847838e+10,1
16,270000010294,47,Claudia,4.012569e+10,1
17,270000010293,220,Liany Dionny,3.877591e+10,1
18,270000010293,47,Cleânia,3.327315e+10,1
19,270000010292,220,Raquel Rosa,3.550880e+10,1
20,270000010292,47,Andrelcia,3.111292e+10,1
21,270000010291,220,Dr. João,4.165904e+10,1
22,270000010291,47,Ana Luiza,3.936819e+10,1
23,270000010290,220,Diany Teles,2.977183e+10,1
24,270000010290,47,Ze Carvalho,2.954846e+10,1
25,1,200412,Adib,5.195905e+10,1
26,1,200412,Ademir Pires,1.729912e+11,1
27,1,200412,Ademir,2.273602e+09,1
28,1,200412,Ademar Peixoto,1.869304e+10,1
29,1,200412,Adelmo Macedo,4.532742e+09,1

In [ ]:
# 2.2 Análise dos duplicados agrupados por nome_urna e sequencial_candidato
print("--- DUPLICADOS POR NOME_URNA E SEQUENCIAL_CANDIDATO ---")
print(
    df_dup_completos
    .groupby(['nome_urna', 'sequencial_candidato'])
    .size()
    .sort_values(ascending=False)
    .reset_index(name='quantidade')
    .head(20)
)

--- DUPLICADOS POR NOME_URNA E SEQUENCIAL_CANDIDATO ---
     nome_urna  sequencial_candidato  quantidade
0     Paulinho                    24           8
1      Marcelo                    28           6
2       Valdir                    94           6
3      Marcelo                    59           6
4       Carlão                    36           6
5    Carlinhos                    75           6
6     Paulinho                    45           6
7    Carlinhos                    78           6
8        Elias                    23           5
9     Paulinho                    48           5
10  Marquinhos                    24           5
11     Valdeci                     7           5
12   Carlinhos                    88           5
13        Neto                    69           5
14     Zezinho                    57           5
15      Edinho                    39           5
16        Lula                     8           5
17      Edinho                    10           5
18   Chiquinho                   118           5
19      Milton                    23           5

In [ ]:
# df_candidatos.to_csv('candidatos.csv', index=False)

### **TABELA DE PESSOAS**

In [ ]:
# 1. Ajuste para tabela do BD
mapeamento = {
    "titulo_eleitoral": "titulo_eleitoral",
    "cpf": "cpf",
    "nome": "nome",
    "data_nascimento": "data_nascimento",
    "genero": "genero",
    "raca": "raca"
}

# 2. Filtrar apenas as colunas desejadas e renomeá-las
df_pessoa = df_deferido[list(mapeamento.keys())].rename(columns=mapeamento).copy()


# Visualizar o resultado
df_pessoa.head()

,titulo_eleitoral,cpf,nome,data_nascimento,genero,raca
0,2.145152e+09,03766489291,Francisco Chagas Da Costa Freitas,1955-03-08,masculino,NaN
1,4.988525e+08,19655924220,Francisco Chagas Benício Dias,1964-04-15,masculino,NaN
2,1.649702e+10,50791524272,Antonia Luciléia Cruz Ramos Câmara,1970-07-17,feminino,NaN
3,1.426382e+09,02190710200,Nilson Moura Leite Mourão,1952-04-01,masculino,NaN
4,2.645724e+08,21630755249,Henrique Afonso Soares Lima,1964-12-03,masculino,NaN

In [ ]:
# Faz o agrupamento, conta as repetições e filtra apenas os que aparecem mais de 1 vez
duplicados = df_pessoa.groupby('titulo_eleitoral').size()
duplicados_acima_de_1 = duplicados[duplicados > 1].sort_values(ascending=False)

# Exibe o resultado
print(f"Total de títulos eleitorais com duplicidade: {len(duplicados_acima_de_1)}")
print("\nExemplo dos títulos que mais se repetem (Título | Quantidade de vezes):")
print(duplicados_acima_de_1.head(20))

Total de títulos eleitorais com duplicidade: 553028

Exemplo dos títulos que mais se repetem (Título | Quantidade de vezes):
titulo_eleitoral
3.843072e+09    12
1.431531e+10    12
3.433801e+10    12
3.397060e+09    12
2.863163e+10    12
1.701442e+09    12
1.200781e+09    12
8.433892e+10    12
2.681897e+11    12
4.469272e+09    12
3.109344e+10    12
1.804162e+09    12
1.388319e+10    12
1.445240e+10    12
5.308661e+10    12
7.756301e+09    12
1.903923e+10    12
1.683386e+11    12
3.666126e+10    11
1.358276e+10    11
dtype: int64

In [ ]:
# Pega o número do título que mais se repetiu no passo anterior e joga aqui para investigar
exemplo_titulo = duplicados_acima_de_1.index[0] # caso queira conferir outros, basta trocar o numero

# Mostra todas as linhas desse mesmo título no arquivo original
df_pessoa[df_pessoa['titulo_eleitoral'] == exemplo_titulo]

,titulo_eleitoral,cpf,nome,data_nascimento,genero,raca
177123,3.843072e+09,32582080187,Emidio Antonio De Souza,1965-08-05,masculino,NaN
276366,3.843072e+09,32582080187,Emidio Antonio De Sousa,1965-08-05,masculino,NaN
326406,3.843072e+09,32582080187,Emidio Antonio De Souza,1965-08-05,masculino,preta
1014825,3.843072e+09,32582080187,Emidio Antônio De Souza,1965-08-05,masculino,preta
1065469,3.843072e+09,32582080187,Emidio Antonio De Souza,1965-08-05,masculino,preta
1080761,3.843072e+09,32582080187,Emidio Antonio De Souza,1965-08-25,masculino,NaN
1207115,3.843072e+09,32582080187,Emidio Antonio De Souza,1965-08-05,masculino,preta
1412739,3.843072e+09,32582080187,Emidio Antônio De Souza,1965-08-05,masculino,NaN
1674464,3.843072e+09,32582080187,Emidio Antonio De Souza,1965-08-05,masculino,preta
2234828,3.843072e+09,32582080187,Emidio Antonio De Souza,1965-08-05,masculino,NaN
2245175,3.843072e+09,32582080187,Emídio Antônio De Souza,1965-08-05,masculino,preta
2728323,3.843072e+09,32582080187,Emidio Antonio De Souza,1965-08-05,masculino,NaN

In [ ]:
# 1. Criar um DataFrame apenas com as pessoas que têm títulos repetidos
# (Pegamos todas as ocorrências delas, não apenas a primeira)
df_duplicados_completos = df_pessoa[df_pessoa['titulo_eleitoral'].duplicated(keep=False)]

# 2. Vamos ver quantas colunas estão vazias (nulas) antes e depois por título
print("--- ANÁLISE DE COMPLEMENTARIDADE ---")
print(f"Total de linhas com títulos repetidos para analisar: {len(df_duplicados_completos)}")

# 3. Contar quantos valores válidos existem por coluna para os títulos repetidos
valores_por_coluna = df_duplicados_completos.groupby('titulo_eleitoral').count()

# Se o valor mínimo de preenchimento for diferente do valor máximo para o mesmo título,
# significa que uma linha tem o dado e a outra não (elas se complementam!)
print("\nExemplo de como as colunas estão preenchidas nos títulos duplicados:")
print(valores_por_coluna.head(10))

--- ANÁLISE DE COMPLEMENTARIDADE ---
Total de linhas com títulos repetidos para analisar: 1540080

Exemplo de como as colunas estão preenchidas nos títulos duplicados:
                  cpf  nome  data_nascimento  genero  raca
titulo_eleitoral
10299.0             2     2                2       2     2
71384.0             4     4                4       4     1
160973.0            6     6                6       6     3
190418.0            2     2                2       2     1
341856.0            3     3                3       3     1
430141.0            4     4                4       4     1
482550.0            2     2                2       2     0
560167.0            6     6                6       6     3
701813.0            2     2                2       2     1
712607.0            2     2                2       2     0

In [ ]:
# Junta as linhas preenchendo os buracos com o primeiro valor válido que encontrar
df_pessoa_combinado = df_pessoa.groupby('titulo_eleitoral').first().reset_index()

# Validação após aglutinar
print(f"\nLinhas restantes após combinar os dados: {len(df_pessoa_combinado)}")
print(f"Duplicados restantes: {df_pessoa_combinado['titulo_eleitoral'].duplicated().sum()}")

Linhas restantes após combinar os dados: 1750411
Duplicados restantes: 0

In [ ]:
# ==========================================
# 1. DIAGNÓSTICO INICIAL
# ==========================================
nulos_antes      = df_pessoa['titulo_eleitoral'].isnull().sum()
duplicados_antes = df_pessoa['titulo_eleitoral'].duplicated().sum()

print("--- DIAGNÓSTICO INICIAL (PESSOA) ---")
print(f"Valores nulos encontrados  : {nulos_antes}")
print(f"Valores duplicados encontrados: {duplicados_antes}")
print(f"Total de linhas no arquivo original: {len(df_pessoa)}\n")

# ==========================================
# 2. LIMPEZA DOS DADOS
# ==========================================

# Passo A: Remover linhas onde a Chave Primária (titulo_eleitoral) é nula
df_pessoa_limpo = df_pessoa_combinado.dropna(subset=['titulo_eleitoral']).copy()

# Passo B: Remover o ".0" gerado quando o título é lido como float
df_pessoa_limpo['titulo_eleitoral'] = (
    df_pessoa_limpo['titulo_eleitoral']
    .astype(str)
    .str.split('.')
    .str[0]
    .str.strip()
)

# ==========================================
# 3. VALIDAÇÃO FINAL
# ==========================================
nulos_depois      = df_pessoa_limpo['titulo_eleitoral'].isnull().sum()
duplicados_depois = df_pessoa_limpo['titulo_eleitoral'].duplicated().sum()

print("--- APÓS A LIMPEZA ---")
print(f"Valores nulos restantes    : {nulos_depois} (Esperado: 0)")
print(f"Valores duplicados restantes: {duplicados_depois} (Esperado: 0)")
print(f"Total de pessoas únicas salvas: {len(df_pessoa_limpo)}\n")

--- DIAGNÓSTICO INICIAL (PESSOA) ---
Valores nulos encontrados  : 695
Valores duplicados encontrados: 987051
Total de linhas no arquivo original: 2737463

--- APÓS A LIMPEZA ---
Valores nulos restantes    : 0 (Esperado: 0)
Valores duplicados restantes: 0 (Esperado: 0)
Total de pessoas únicas salvas: 1750411

In [ ]:
df_pessoa_limpo.to_csv('/content/Pessoas_Limpo.csv', index=False)
print("Sucesso! O arquivo 'Pessoas_Limpo.csv' foi gerado e está pronto para o banco.")

Sucesso! O arquivo 'Pessoas_Limpo.csv' foi gerado e está pronto para o banco.

### **TABELA DE ELEICAO**

In [ ]:
# 1. Ajuste para tabela do BD
mapeamento = {
    "id_eleicao": "id_eleicao",
    "ano": "ano",
    "tipo_eleicao": "tipo_eleicao",
    "data_eleicao": "data_eleicao"
}

# 2. Filtrar apenas as colunas desejadas e renomeá-las

df_deferido_eleicao = df_deferido[list(mapeamento.keys())].rename(columns=mapeamento).drop_duplicates().copy()
df_deferido_eleicao.reset_index(inplace=True)
df_deferido_eleicao = df_deferido_eleicao.drop(columns=['index'])

# Visualizar o resultado
df_deferido_eleicao.head()

   id_eleicao   ano                      tipo_eleicao data_eleicao
0     2006001  2006                 eleicao ordinaria   2006-10-01
1         297  2018                 eleicao ordinaria   2018-10-07
2         438  2018  eleicao suplementar senador - mt   2020-11-15
3         295  2018                 eleicao ordinaria   2018-10-07
4          30  2008                 eleicao ordinaria   2008-10-05

In [ ]:
# ==========================================
# ANÁLISE DE DUPLICATAS (ELEIÇÃO)
# ==========================================

# 1. Identificar duplicatas
duplicados_eleicao = df_deferido_eleicao.groupby('id_eleicao').size()
duplicados_acima_de_1 = duplicados_eleicao[duplicados_eleicao > 1].sort_values(ascending=False)

print(f"Total de id_eleicao com duplicidade: {len(duplicados_acima_de_1)}")
print("\nExemplo dos que mais se repetem (id_eleicao | Quantidade):")
print(duplicados_acima_de_1.head(20))

Total de id_eleicao com duplicidade: 2

Exemplo dos que mais se repetem (id_eleicao | Quantidade):
id_eleicao
32    60
39     2
dtype: int64

In [ ]:
# 2. Investigar um exemplo para verificar se as linhas se complementam
exemplo_id = duplicados_acima_de_1.index[0]  # caso queira conferir outros, basta trocar o numero
df_deferido_eleicao[df_deferido_eleicao['id_eleicao'] == exemplo_id]

     id_eleicao   ano                 tipo_eleicao data_eleicao
5            32  2008  eleicoes suplementares 2008   2009-03-15
6            32  2008  eleicoes suplementares 2008   2010-03-07
7            32  2008  eleicoes suplementares 2008   2009-12-27
8            32  2008  eleicoes suplementares 2008   2010-11-07
9            32  2008  eleicoes suplementares 2008   2010-05-30
10           32  2008  eleicoes suplementares 2008   2009-03-29
11           32  2008  eleicoes suplementares 2008   2009-03-01
12           32  2008  eleicoes suplementares 2008   2009-12-06
13           32  2008  eleicoes suplementares 2008   2009-03-22
14           32  2008  eleicoes suplementares 2008   2010-05-02
15           32  2008  eleicoes suplementares 2008   2009-03-08
17           32  2008  eleicoes suplementares 2008   2009-07-26
18           32  2008  eleicoes suplementares 2008   2011-06-05
48           32  2008  eleicoes suplementares 2008   2011-07-03
96           32  2008  eleicoes suplementares 2008   2009-11-08
97           32  2008  eleicoes suplementares 2008   2010-12-05
98           32  2008  eleicoes suplementares 2008   2010-07-18
99           32  2008  eleicoes suplementares 2008   2011-07-31
100          32  2008  eleicoes suplementares 2008   2010-08-08
101          32  2008  eleicoes suplementares 2008   2011-08-07
102          32  2008  eleicoes suplementares 2008   2012-01-29
103          32  2008  eleicoes suplementares 2008   2012-03-04
104          32  2008  eleicoes suplementares 2008   2009-02-15
105          32  2008  eleicoes suplementares 2008   2011-07-24
106          32  2008  eleicoes suplementares 2008   2010-12-19
107          32  2008  eleicoes suplementares 2008   2009-04-26
108          32  2008  eleicoes suplementares 2008   2011-07-17
126          32  2008  eleicoes suplementares 2008   2010-06-06
159          32  2008  eleicoes suplementares 2008   2010-04-11
160          32  2008  eleicoes suplementares 2008   2009-05-31
161          32  2008  eleicoes suplementares 2008   2011-10-02
162          32  2008  eleicoes suplementares 2008   2009-02-08
164          32  2008  eleicoes suplementares 2008   2009-09-13
165          32  2008  eleicoes suplementares 2008   2010-09-05
177          32  2008  eleicoes suplementares 2008   2011-11-13
206          32  2008  eleicoes suplementares 2008   2009-10-11
207          32  2008  eleicoes suplementares 2008   2012-04-01
208          32  2008  eleicoes suplementares 2008   2009-12-13
209          32  2008  eleicoes suplementares 2008   2009-11-15
210          32  2008  eleicoes suplementares 2008   2011-09-04
249          32  2008  eleicoes suplementares 2008   2011-10-30
250          32  2008  eleicoes suplementares 2008   2011-11-06
251          32  2008  eleicoes suplementares 2008   2009-10-04
252          32  2008  eleicoes suplementares 2008   2011-04-03
272          32  2008  eleicoes suplementares 2008   2009-04-19
294          32  2008  eleicoes suplementares 2008   2008-12-21
295          32  2008  eleicoes suplementares 2008   2011-12-11
296          32  2008  eleicoes suplementares 2008   2009-05-17
350          32  2008  eleicoes suplementares 2008   2010-06-13
359          32  2008  eleicoes suplementares 2008   2010-06-20
395          32  2008  eleicoes suplementares 2008   2009-09-20
396          32  2008  eleicoes suplementares 2008   2011-10-09
397          32  2008  eleicoes suplementares 2008   2009-07-12
398          32  2008  eleicoes suplementares 2008   2010-03-28
399          32  2008  eleicoes suplementares 2008   2009-01-25
400          32  2008  eleicoes suplementares 2008   2011-11-20
401          32  2008  eleicoes suplementares 2008   2008-12-14
416          32  2008  eleicoes suplementares 2008   2011-01-30
436          32  2008  eleicoes suplementares 2008   2011-02-20
437          32  2008  eleicoes suplementares 2008   2010-02-28

In [ ]:
# 3. Análise de complementaridade entre as colunas das duplicatas
df_dup_completos = df_deferido_eleicao[df_deferido_eleicao['id_eleicao'].duplicated(keep=False)]

print("--- ANÁLISE DE COMPLEMENTARIDADE ---")
print(f"Total de linhas com id_eleicao repetido para analisar: {len(df_dup_completos)}")

valores_por_coluna = df_dup_completos.groupby('id_eleicao').count()
print("\nExemplo de como as colunas estão preenchidas nos duplicados:")
print(valores_por_coluna.head(10))

--- ANÁLISE DE COMPLEMENTARIDADE ---
Total de linhas com id_eleicao repetido para analisar: 62

Exemplo de como as colunas estão preenchidas nos duplicados:
            ano  tipo_eleicao  data_eleicao
id_eleicao
32           60            60            60
39            2             2             2

In [ ]:
# 4. Combinar aproveitando o primeiro valor válido de cada campo
df_eleicao_combinado = df_deferido_eleicao.groupby('id_eleicao').first().reset_index()

print(f"Linhas restantes após combinar os dados: {len(df_eleicao_combinado)}")
print(f"Duplicados restantes: {df_eleicao_combinado['id_eleicao'].duplicated().sum()}")

Linhas restantes após combinar os dados: 488
Duplicados restantes: 0

In [ ]:
# ==========================================
# 1. DIAGNÓSTICO INICIAL
# ==========================================
nulos_antes      = df_deferido_eleicao['id_eleicao'].isnull().sum()
duplicados_antes = df_deferido_eleicao['id_eleicao'].duplicated().sum()

print("--- DIAGNÓSTICO INICIAL (ELEIÇÃO) ---")
print(f"Valores nulos encontrados  : {nulos_antes}")
print(f"Valores duplicados encontrados: {duplicados_antes}")
print(f"Total de linhas no arquivo original: {len(df_deferido_eleicao)}\n")

# ==========================================
# 2. LIMPEZA DOS DADOS
# ==========================================

# Passo A: Remover linhas onde a Chave Primária (id_eleicao) é nula
df_eleicao_limpo = df_eleicao_combinado.dropna(subset=['id_eleicao']).copy()

# Passo B: Garantir que id_eleicao seja inteiro sem decimais
df_eleicao_limpo['id_eleicao'] = (
    df_eleicao_limpo['id_eleicao']
    .astype(str)
    .str.split('.')
    .str[0]
    .str.strip()
)

# ==========================================
# 3. VALIDAÇÃO FINAL
# ==========================================
nulos_depois      = df_eleicao_limpo['id_eleicao'].isnull().sum()
duplicados_depois = df_eleicao_limpo['id_eleicao'].duplicated().sum()

print("--- APÓS A LIMPEZA ---")
print(f"Valores nulos restantes    : {nulos_depois} (Esperado: 0)")
print(f"Valores duplicados restantes: {duplicados_depois} (Esperado: 0)")
print(f"Total de eleições únicas salvas: {len(df_eleicao_limpo)}\n")

--- DIAGNÓSTICO INICIAL (ELEIÇÃO) ---
Valores nulos encontrados  : 0
Valores duplicados encontrados: 60
Total de linhas no arquivo original: 548

--- APÓS A LIMPEZA ---
Valores nulos restantes    : 0 (Esperado: 0)
Valores duplicados restantes: 0 (Esperado: 0)
Total de eleições únicas salvas: 488

In [ ]:
df_eleicao_limpo.to_csv('/content/Eleicao_Limpo.csv', index=False)
print("Sucesso! O arquivo 'Eleicao_Limpo.csv' foi gerado e está pronto para o banco.")

Sucesso! O arquivo 'Eleicao_Limpo.csv' foi gerado e está pronto para o banco.

### **TABELA DE PARTIDO**

In [ ]:
# 1. Ajuste para tabela do BD
mapeamento = {
    "numero_partido": "numero_partido",
    "sigla_partido": "sigla"
}

# 2. Filtrar apenas as colunas desejadas e renomeá-las

df_deferido_partido = df_deferido[list(mapeamento.keys())].rename(columns=mapeamento).drop_duplicates(subset=['numero_partido'], keep='first').copy()
df_deferido_partido.reset_index(inplace=True)
df_deferido_partido = df_deferido_partido.drop(columns=['index'])

# Visualizar o resultado
df_deferido_partido.head()

   numero_partido sigla
0              25   PFL
1              27  PSDC
2              11    PP
3              13    PT
4              23   PPS

In [ ]:
# 1. Verificar se existem valores nulos na chave do partido
nulos_partido = df_deferido_partido['numero_partido'].isnull().sum()
print(f"Valores nulos encontrados: {nulos_partido}")

# 2. Verificar se existem valores duplicados (já que ela será uma Primary Key)
duplicados_partido = df_deferido_partido['numero_partido'].duplicated().sum()
print(f"Valores duplicados encontrados: {duplicados_partido}")

Valores nulos encontrados: 0
Valores duplicados encontrados: 0

In [ ]:
# df_deferido_partido.to_csv('partido.csv', index=False)

### **TABELA DE MUNICIPIOS**

In [ ]:
df.columns

Index(['ano', 'id_eleicao', 'tipo_eleicao', 'data_eleicao', 'sigla_uf',
       'id_municipio', 'id_municipio_tse', 'titulo_eleitoral', 'cpf',
       'sequencial', 'numero', 'nome', 'nome_urna', 'numero_partido',
       'sigla_partido', 'cargo', 'situacao', 'data_nascimento', 'idade',
       'genero', 'instrucao', 'ocupacao', 'estado_civil', 'nacionalidade',
       'sigla_uf_nascimento', 'municipio_nascimento', 'email', 'raca'],
      dtype='object')

In [ ]:
df_municipio = pd.read_csv('https://raw.githubusercontent.com/danielIESB/Trabalho-Projeto-Eleicao/331f19fb7362f45847f748289f2079447ccf82ee/municipio_tse_ibge.csv', sep=';', encoding='latin1')

In [ ]:
df_municipio.head()

,DT_GERACAO,HH_GERACAO,CD_UF_TSE,CD_UF_IBGE,SG_UF,NM_UF,CD_MUNICIPIO_TSE,NM_MUNICIPIO_TSE,CD_MUNICIPIO_IBGE,NM_MUNICIPIO_IBGE
0,10/05/2026,09:01:10,24,12,AC,Acre,1007,Bujari,1200138,Bujari
1,10/05/2026,09:01:10,24,12,AC,Acre,1015,Capixaba,1200179,Capixaba
2,10/05/2026,09:01:10,24,12,AC,Acre,1023,Porto Acre,1200807,Porto Acre
3,10/05/2026,09:01:10,24,12,AC,Acre,1031,Santa Rosa Do Purus,1200435,Santa Rosa Do Purus
4,10/05/2026,09:01:10,24,12,AC,Acre,1040,Marechal Thaumaturgo,1200351,Marechal Thaumaturgo

In [ ]:
municipio_candidatos = df_deferido[['id_municipio']].drop_duplicates().copy()
municipio_candidatos.reset_index(inplace=True)
municipio_candidatos = municipio_candidatos.drop(columns=['index'])
municipio_candidatos.head()

   id_municipio
0           NaN
1     1100049.0
2     1100098.0
3     1100114.0
4     1100304.0

In [ ]:
df_municipio['CD_MUNICIPIO_IBGE'] = df_municipio['CD_MUNICIPIO_IBGE'].astype(float)
joined_municipios = pd.merge(municipio_candidatos, df_municipio, left_on='id_municipio', right_on='CD_MUNICIPIO_IBGE', how='inner')
display(joined_municipios.head())

,id_municipio,DT_GERACAO,HH_GERACAO,CD_UF_TSE,CD_UF_IBGE,SG_UF,NM_UF,CD_MUNICIPIO_TSE,NM_MUNICIPIO_TSE,CD_MUNICIPIO_IBGE,NM_MUNICIPIO_IBGE
0,1100049.0,10/05/2026,09:01:10,23,11,RO,Rondônia,94,Cacoal,1100049.0,Cacoal
1,1100098.0,10/05/2026,09:01:10,23,11,RO,Rondônia,256,Espigão Do Oeste,1100098.0,Espigão D'Oeste
2,1100114.0,10/05/2026,09:01:10,23,11,RO,Rondônia,159,Jaru,1100114.0,Jaru
3,1100304.0,10/05/2026,09:01:10,23,11,RO,Rondônia,132,Vilhena,1100304.0,Vilhena
4,1100338.0,10/05/2026,09:01:10,23,11,RO,Rondônia,434,Nova Mamoré,1100338.0,Nova Mamoré

In [ ]:
joined_municipios = joined_municipios.drop(columns=[
  'DT_GERACAO',
  'HH_GERACAO',
  'CD_UF_TSE',
  'CD_UF_IBGE',
  'NM_UF',
  'CD_MUNICIPIO_IBGE',
  'NM_MUNICIPIO_IBGE'
])
joined_municipios.head()

   id_municipio SG_UF  CD_MUNICIPIO_TSE  NM_MUNICIPIO_TSE
0     1100049.0    RO                94            Cacoal
1     1100098.0    RO               256  Espigão Do Oeste
2     1100114.0    RO               159              Jaru
3     1100304.0    RO               132           Vilhena
4     1100338.0    RO               434       Nova Mamoré

In [ ]:
joined_municipios.columns

Index(['id_municipio', 'SG_UF', 'CD_MUNICIPIO_TSE', 'NM_MUNICIPIO_TSE'], dtype='object')

In [ ]:
# joined_municipios.to_csv('municipios.csv', index=False)