In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Despesas_Candidatos_Presidente_Governador.csv', engine='python', on_bad_lines='skip')

In [ ]:
df.head()

,ano,turno,id_eleicao,tipo_eleicao,data_eleicao,sigla_uf,sigla_uf_nome,id_municipio,id_municipio_nome,id_municipio_tse,...,descricao_cnae_2_fornecedor,tipo_fornecedor,esfera_partidaria_fornecedor,sigla_uf_fornecedor,id_municipio_tse_fornecedor,sequencial_candidato_fornecedor,numero_candidato_fornecedor,numero_partido_fornecedor,sigla_partido_fornecedor,cargo_fornecedor
0,2010,NaN,NaN,eleicao ordinaria,NaN,AC,Acre,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010,NaN,NaN,eleicao ordinaria,NaN,AC,Acre,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010,NaN,NaN,eleicao ordinaria,NaN,AL,Alagoas,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,NaN,NaN,eleicao ordinaria,NaN,AL,Alagoas,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,NaN,NaN,eleicao ordinaria,NaN,AL,Alagoas,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Acrescentei uma coluno com o tipo de "transação" para importação na tabela Receitas e Despesas no banco de dados.
df['Tipo'] = 'D'

In [ ]:
df.head()

,ano,turno,id_eleicao,tipo_eleicao,data_eleicao,sigla_uf,sigla_uf_nome,id_municipio,id_municipio_nome,id_municipio_tse,...,tipo_fornecedor,esfera_partidaria_fornecedor,sigla_uf_fornecedor,id_municipio_tse_fornecedor,sequencial_candidato_fornecedor,numero_candidato_fornecedor,numero_partido_fornecedor,sigla_partido_fornecedor,cargo_fornecedor,Tipo
0,2010,NaN,NaN,eleicao ordinaria,NaN,AC,Acre,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D
1,2010,NaN,NaN,eleicao ordinaria,NaN,AC,Acre,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D
2,2010,NaN,NaN,eleicao ordinaria,NaN,AL,Alagoas,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D
3,2010,NaN,NaN,eleicao ordinaria,NaN,AL,Alagoas,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D
4,2010,NaN,NaN,eleicao ordinaria,NaN,AL,Alagoas,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D

In [ ]:
df.columns

Index(['ano', 'turno', 'id_eleicao', 'tipo_eleicao', 'data_eleicao',
       'sigla_uf', 'sigla_uf_nome', 'id_municipio', 'id_municipio_nome',
       'id_municipio_tse', 'id_municipio_tse_nome',
       'titulo_eleitoral_candidato', 'sequencial_candidato',
       'numero_candidato', 'cnpj_candidato', 'numero_partido', 'sigla_partido',
       'cargo', 'sequencial_despesa', 'data_despesa', 'tipo_despesa',
       'descricao_despesa', 'origem_despesa', 'valor_despesa',
       'tipo_prestacao_contas', 'data_prestacao_contas',
       'sequencial_prestador_contas', 'cnpj_prestador_contas',
       'tipo_documento', 'numero_documento', 'especie_recurso',
       'fonte_recurso', 'cpf_cnpj_fornecedor', 'nome_fornecedor',
       'nome_fornecedor_rf', 'cnae_2_fornecedor', 'cnae_2_fornecedor_classe',
       'cnae_2_fornecedor_subclasse',
       'cnae_2_fornecedor_subclasse_descricao_subclasse',
       'cnae_2_fornecedor_subclasse_descricao_classe',
       'cnae_2_fornecedor_subclasse_descricao_grupo',
       'cnae_2_fornecedor_subclasse_descricao_divisao',
       'cnae_2_fornecedor_subclasse_descricao_secao',
       'descricao_cnae_2_fornecedor', 'tipo_fornecedor',
       'esfera_partidaria_fornecedor', 'sigla_uf_fornecedor',
       'id_municipio_tse_fornecedor', 'sequencial_candidato_fornecedor',
       'numero_candidato_fornecedor', 'numero_partido_fornecedor',
       'sigla_partido_fornecedor', 'cargo_fornecedor', 'Tipo'],
      dtype='object')

In [ ]:
# 1. Ajuste para tabela do BD
mapeamento = {
    'sequencial_despesa': 'sequencial',
    'sequencial_candidato': 'sequencial_candidato',
    'cpf_cnpj_fornecedor': 'cpf_cnpj_doador',
    'data_despesa': 'dthora_transacao',
    'valor_despesa': 'valor_transacao',
    'origem_despesa': 'origem',
    'tipo_despesa': 'natureza',
    'especie_recurso': 'especie',
    'numero_documento': 'numero_documento',
    'descricao_despesa': 'descricao_despesa',
    'Tipo': 'tipo_transacao'
}

# 2. Filtrar apenas as colunas desejadas e renomeá-las
df_receita_despesa = df[list(mapeamento.keys())].rename(columns=mapeamento).copy()

# 3. Converter dthora_transacao para o formato datetime se necessário, ignorando erros
df_receita_despesa['dthora_transacao'] = pd.to_datetime(df_receita_despesa['dthora_transacao'], errors='coerce')

# Visualizar o resultado
df_receita_despesa.head()

,sequencial,sequencial_candidato,cpf_cnpj_doador,dthora_transacao,valor_transacao,origem,natureza,especie,numero_documento,descricao_despesa,tipo_transacao
0,NaN,10000000130,79727956220,2010-08-10,700.0,NaN,despesas com pessoal,cheque,01,"41 DIAS DE SERVIÇOS COM PANFLETAGEM"" ...",D
1,NaN,10000000130,46126015215,2010-08-16,1950.0,NaN,cessao ou locacao de veiculos,cheque,01,ALUGUEL DE UM FIAT UNO MILLE DE COR VERDE DURA...,D
2,NaN,20000000059,06329986444,2010-09-26,20.0,NaN,despesas com pessoal,cheque,SN,"PAGAMENTO SERVIÇOS PRSTADOS POR BANDEIRINHAS, ...",D
3,NaN,20000000059,07773660450,2010-10-02,255.0,NaN,despesas com pessoal,cheque,SN,PAGAMENTO REFERENTE A TRABALHOS EXECUTADOS NO ...,D
4,NaN,20000000059,09095052000163,2010-09-24,250000.0,NaN,producao de programas de radio televisao ou video,cheque,161,PRODUÇÃO DE VT'S PARA PUBLICIDADE DE RADIO E T...,D

In [ ]:
df_receita_despesa.to_csv('/content/receitas_despesas.csv', index=False)